### ISSUE TITLE
"<param name="simulation_data_1"...>,

### ISSUE THREAD

**Issue by fanshuCzz** [MAPIRlab/Gas-Source-Localization#10]
Hello, when I run the main version of ROS1_ I found that it kept reminding me that a certain file was missing. After checking, I found that there is a sentence in "~/PMFS/A/launch/A1/main_simbot. launch"<param name="simulation_data_1"...>, but the corresponding "gas_simulations" file is missing from the package.I wonder where to get this file from?

**Comment by PepeOjeda** [comment]
The gas simulation results are not distributed directly, as they take quite a bit of space and are easy for you to generate. All you have to do is run `GADEN_preprocessing.launch` and `GADEN.launch` for that specific scenario before you run `main_simbot.launch`.

As a sidenote, if you plan to use the PMFS algorithm specifically, there might be a little adjustment that you need to make to the occupancy map image that is generated by `preprocessing` -- where you open `occupancy.pgm` with some editing program (*e.g.* GIMP) and make sure that the outlets and inlets are marked as free space all the way to the edge of the image. I know this is clunky, but it's really not trivial to fully automate.
