### ISSUE TITLE
wrong on #include <gmrf_wind_mapping/srv/wind_estimation.hpp>

### ISSUE THREAD

**Issue by Qwxmwdncjwncc** [MAPIRlab/Gas-Source-Localization#11]
Hello, I have downloaded the GSL required tool package, and encountered an error when compiling in the ROS 2 workspace using colcon. I couldn't find the file related to #include <gmrf_wind_mapping/srv/wind_estimation.hpp> in GMRF-wind. Thank you very much for your assistance, and I would greatly appreciate it if I could receive your answer.
![屏幕截图 2024-11-26 153451](https://github.com/user-attachments/assets/0a1aeb3e-9bcc-4401-a859-18eebfb10113)
![屏幕截图 2024-11-26 153520](https://github.com/user-attachments/assets/03ab005d-b326-45a8-93f9-5673eb06c574)

**Comment by PepeOjeda** [comment]
Hello. That file is an auto-generated header that colcon creates from the `.srv`  files in the GMRF package, which is why you cannot find it in the source directories. 
I cannot reproduce this problem, and looking at the configuration it seems to me that the dependency is correctly specified, so I'm not sure what the cause may be. You could try to compile the GMRF  package by itself first with 

`colcon build --symlink-install --packages-select gmrf_wind_mapping`

, to make sure they are compiled in the right order (but, again, this should be happening automatically).

**Comment by Qwxmwdncjwncc** [comment]
Thank you for your response, but there are still issues：

wyx@WUYX:~/gaden_ws$ colcon build --symlink-install --packages-select gmrf_wind_mapping
Starting >>> gmrf_wind_mapping
Finished <<< gmrf_wind_mapping [10.2s]                       

Summary: 1 package finished [10.5s]
wyx@WUYX:~/gaden_ws$ colcon build
Starting >>> gaden_common
Starting >>> olfaction_msgs
Starting >>> gmrf_msgs
Starting >>> gsl_actions
Starting >>> ament_imgui
Starting >>> gaden_preprocessing
Starting >>> grgsl_env
Starting >>> pmfs_env
Starting >>> test_env
Finished <<< grgsl_env [0.88s]                                      
Finished <<< gaden_common [0.93s]
Finished <<< pmfs_env [0.89s]
Starting >>> gaden_player
Starting >>> gaden_environment
Starting >>> OccupancyGridToSTL
Starting >>> gaden_decompress
Starting >>> gaden_filament_simulator
Finished <<< gaden_preprocessing [0.97s]
Finished <<< test_env [0.97s]                                             
Finished <<< ament_imgui [1.39s]                                         
Finished <<< gmrf_msgs [1.49s]                                        
[2.042s] WARNING:colcon.colcon_cmake.task.cmake.build:Could not run installation step for package 'OccupancyGridToSTL' because it has no 'install' target
Finished <<< OccupancyGridToSTL [0.58s]                               
Finished <<< gsl_actions [1.53s]
Finished <<< gaden_decompress [0.70s]                                 
Finished <<< gaden_filament_simulator [0.71s]
Finished <<< olfaction_msgs [1.71s]
Starting >>> gmrf_wind_mapping                                          
Finished <<< gaden_environment [1.09s]                                  
Finished <<< gaden_player [1.16s]
Starting >>> simulated_anemometer
Starting >>> simulated_gas_sensor
Starting >>> simulated_tdlas
Finished <<< simulated_gas_sensor [0.63s]                               
Finished <<< simulated_anemometer [0.67s]                               
Finished <<< simulated_tdlas [0.93s]                                    
Finished <<< gmrf_wind_mapping [10.4s]                      
Starting >>> gsl_server
--- stderr: gsl_server                                 
In file included from /home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/PMFS/PMFS.hpp:6,
                 from /home/wyx/gaden_ws/src/GSL/gsl_server/src/server/algorithms/PMFS/MovingStatePMFS.cpp:2:
/home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/PMFS/internal/PublishersAndSubscribers.hpp:6:10: fatal error: gmrf_wind_mapping/srv/wind_estimation.hpp: No such file or directory
    6 | #include <gmrf_wind_mapping/srv/wind_estimation.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/wyx/gaden_ws/src/GSL/gsl_server/src/server/algorithms/GrGSL/GrGSL.cpp:1:
/home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/GrGSL/GrGSL.hpp:4:10: fatal error: gmrf_wind_mapping/srv/wind_estimation.hpp: No such file or directory
    4 | #include <gmrf_wind_mapping/srv/wind_estimation.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/gsl_actionserver_node.dir/build.make:216: CMakeFiles/gsl_actionserver_node.dir/src/server/algorithms/PMFS/MovingStatePMFS.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [CMakeFiles/gsl_actionserver_node.dir/build.make:188: CMakeFiles/gsl_actionserver_node.dir/src/server/algorithms/GrGSL/GrGSL.cpp.o] Error 1
In file included from /home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/PMFS/PMFS.hpp:6,
                 from /home/wyx/gaden_ws/src/GSL/gsl_server/src/server/algorithms/PMFS/PMFS_core.cpp:1:
/home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/PMFS/internal/PublishersAndSubscribers.hpp:6:10: fatal error: gmrf_wind_mapping/srv/wind_estimation.hpp: No such file or directory
    6 | #include <gmrf_wind_mapping/srv/wind_estimation.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/PMFS/PMFS.hpp:6,
                 from /home/wyx/gaden_ws/src/GSL/gsl_server/src/server/algorithms/PMFS/UI.cpp:3:
/home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/PMFS/internal/PublishersAndSubscribers.hpp:6:10: fatal error: gmrf_wind_mapping/srv/wind_estimation.hpp: No such file or directory
    6 | #include <gmrf_wind_mapping/srv/wind_estimation.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/gsl_actionserver_node.dir/build.make:230: CMakeFiles/gsl_actionserver_node.dir/src/server/algorithms/PMFS/PMFS_core.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/gsl_actionserver_node.dir/build.make:300: CMakeFiles/gsl_actionserver_node.dir/src/server/algorithms/PMFS/UI.cpp.o] Error 1
In file included from /home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/GrGSL/MovingStateGrGSL.hpp:4,
                 from /home/wyx/gaden_ws/src/GSL/gsl_server/src/server/algorithms/GrGSL/MovingStateGrGSL.cpp:1:
/home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/GrGSL/GrGSL.hpp:4:10: fatal error: gmrf_wind_mapping/srv/wind_estimation.hpp: No such file or directory
    4 | #include <gmrf_wind_mapping/srv/wind_estimation.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/gsl_actionserver_node.dir/build.make:202: CMakeFiles/gsl_actionserver_node.dir/src/server/algorithms/GrGSL/MovingStateGrGSL.cpp.o] Error 1
In file included from /home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/PMFS/PMFS.hpp:6,
                 from /home/wyx/gaden_ws/src/GSL/gsl_server/src/server/algorithms/PMFS/Simulations.cpp:2:
/home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/PMFS/internal/PublishersAndSubscribers.hpp:6:10: fatal error: gmrf_wind_mapping/srv/wind_estimation.hpp: No such file or directory
    6 | #include <gmrf_wind_mapping/srv/wind_estimation.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/gsl_actionserver_node.dir/build.make:286: CMakeFiles/gsl_actionserver_node.dir/src/server/algorithms/PMFS/Simulations.cpp.o] Error 1
In file included from /home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/PMFS/PMFS.hpp:6,
                 from /home/wyx/gaden_ws/src/GSL/gsl_server/src/server/algorithms/PMFS/PMFS_initialization.cpp:1:
/home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/PMFS/internal/PublishersAndSubscribers.hpp:6:10: fatal error: gmrf_wind_mapping/srv/wind_estimation.hpp: No such file or directory
    6 | #include <gmrf_wind_mapping/srv/wind_estimation.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/gsl_actionserver_node.dir/build.make:244: CMakeFiles/gsl_actionserver_node.dir/src/server/algorithms/PMFS/PMFS_initialization.cpp.o] Error 1
In file included from /home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/PMFS/PMFS.hpp:6,
                 from /home/wyx/gaden_ws/src/GSL/gsl_server/src/server/algorithms/PMFS/PMFS_visualization.cpp:1:
/home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/PMFS/internal/PublishersAndSubscribers.hpp:6:10: fatal error: gmrf_wind_mapping/srv/wind_estimation.hpp: No such file or directory
    6 | #include <gmrf_wind_mapping/srv/wind_estimation.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/gsl_actionserver_node.dir/build.make:272: CMakeFiles/gsl_actionserver_node.dir/src/server/algorithms/PMFS/PMFS_visualization.cpp.o] Error 1
In file included from /home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/PMFS/PMFS.hpp:6,
                 from /home/wyx/gaden_ws/src/GSL/gsl_server/src/server/algorithms/PMFS/PMFS_utils.cpp:1:
/home/wyx/gaden_ws/src/GSL/gsl_server/include/gsl_server/algorithms/PMFS/internal/PublishersAndSubscribers.hpp:6:10: fatal error: gmrf_wind_mapping/srv/wind_estimation.hpp: No such file or directory
    6 | #include <gmrf_wind_mapping/srv/wind_estimation.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/gsl_actionserver_node.dir/build.make:258: CMakeFiles/gsl_actionserver_node.dir/src/server/algorithms/PMFS/PMFS_utils.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/gsl_actionserver_node.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< gsl_server [21.8s, exited with code 2]

Summary: 18 packages finished [34.3s]
  1 package failed: gsl_server
  1 package had stderr output: gsl_server
![image](https://github.com/user-attachments/assets/48665668-50bf-4920-81dc-790f0d8f108a)

**Comment by PepeOjeda** [comment]
Ah, I see what the problem is. The main branch was still using an older version of the gmrf repository, but the github repo of gmrf had been updated since. I've updated this repository to use the newest version of the gmrf package now.

**Comment by Qwxmwdncjwncc** [comment]
> Ah, I see what the problem is. The main branch was still using an older version of the gmrf repository, but the github repo of gmrf had been updated since. I've updated this repository to use the newest version of the gmrf package now.

Thank you very much for your help, I have successfully compiled it.
