### ISSUE TITLE
how to run node？

### ISSUE THREAD

**Issue by Qwxmwdncjwncc** [MAPIRlab/Gas-Source-Localization#12]
Is the example run by sequentially executing the three files in the launch folder under Exp_A:
GADEN_preprocessing.launch
GADEN.launch
main_simbot.py

Another question is how to launch the gsl_actionserver_node node.
Thank you.
![image](https://github.com/user-attachments/assets/b1e49c1c-b278-43a0-9899-0efa70e46a44)
![image](https://github.com/user-attachments/assets/b68e75a7-d88a-4696-a4e1-bde44bf074c5)

**Comment by songyuri** [comment]
How did you solve it? How can I run?

**Comment by shuaidongwang334-web** [comment]
> Is the example run by sequentially executing the three files in the launch folder under Exp_A: GADEN_preprocessing.launch GADEN.launch main_simbot.py
> 
> Another question is how to launch the gsl_actionserver_node node. Thank you. ![image](https://github.com/user-attachments/assets/b1e49c1c-b278-43a0-9899-0efa70e46a44) ![image](https://github.com/user-attachments/assets/b68e75a7-d88a-4696-a4e1-bde44bf074c5)

请问您可以告诉我解决方法吗
