### ISSUE TITLE
[rviz2-1]: process has died

### ISSUE THREAD

**Issue by Qwxmwdncjwncc** [MAPIRlab/Gas-Source-Localization#13]
### first I launch GSL/Environment_config/PMFS/launch/gaden_preproc_launch.py,and it work.
[preprocessing-1] [INFO] [1733380219.262999844] [GadenPreprocessing]: 65%
[preprocessing-1] [INFO] [1733380219.273591091] [GadenPreprocessing]: 90%
[preprocessing-1] [INFO] [1733380219.756725938] [GadenPreprocessing]: Preprocessing done

### But when I run `gaden_sim_launch.py`, rviz2 shows the environment for about 5 seconds and then suddenly exits, with the page closing by itself. I'm not sure if you've encountered the same problem. Thank you.

(one) (base) wyx@WUYX:~/gaden_ws$ ros2 launch src/GSL/Environment_config/PMFS/launch/gaden_sim_launch.py
[INFO] [launch]: All log files can be found below /home/wyx/.ros/log/2024-12-05-14-30-22-963062-WUYX-1207
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rviz2-1]: process started with pid [1208]
[INFO] [environment-2]: process started with pid [1210]
[INFO] [filament_simulator-3]: process started with pid [1212]
[environment-2] [INFO] [1733380223.194319339] [Environment]: The data provided in the roslaunch file is:
[environment-2] [INFO] [1733380223.194449994] [Environment]: wait_preprocessing: false
[environment-2] [INFO] [1733380223.194463709] [Environment]: Fixed Frame: map
[environment-2] [INFO] [1733380223.194471995] [Environment]: number_of_sources: 1
[environment-2] [INFO] [1733380223.194519714] [Environment]: Gas_source(0): pos=[5.00 6.20 0.50] scale=0.20color=[0.00 1.00 0.00]
[environment-2] [INFO] [1733380223.194612678] [Environment]: number_of_CAD: 2
[environment-2] [INFO] [1733380223.194641161] [Environment]: Occupancy3D file location: /home/wyx/gaden_ws/install/pmfs_env/share/pmfs_env/scenarios/A/OccupancyGrid3D.csv
[rviz2-1] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-wyx'
[filament_simulator-3] [WARN] [1733380223.265665113] [FilamentSimulator]: File /home/wyx/gaden_ws/install/pmfs_env/share/pmfs_env/scenarios/A/wind_simulations/1,2,3-5,6_1.csv_U Does Not Exists!
[filament_simulator-3] [WARN] [1733380223.265857843] [FilamentSimulator]: No more wind data available. Using last Wind snapshopt as SteadyState.
[rviz2-1] [INFO] [1733380223.691143088] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1733380223.691464269] [rviz2]: OpenGl version: 4.5 (GLSL 4.5)
[rviz2-1] [INFO] [1733380223.720993681] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [WARN] [1733380223.832283246] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[filament_simulator-3] [INFO] [1733380231.332881213] [FilamentSimulator]: Filament simulator finished correctly!
[INFO] [filament_simulator-3]: process has finished cleanly [pid 1212]
[INFO] [launch]: process[filament_simulator-3] was required: shutting down launched system
[INFO] [environment-2]: sending signal 'SIGINT' to process[environment-2]
[INFO] [rviz2-1]: sending signal 'SIGINT' to process[rviz2-1]
[environment-2] [INFO] [1733380231.449128260] [rclcpp]: signal_handler(signum=2)
[rviz2-1] [INFO] [1733380231.449815437] [rclcpp]: signal_handler(signum=2)
[ERROR] [rviz2-1]: process has died [pid 1208, exit code -11, cmd '/opt/ros/humble/lib/rviz2/rviz2 -d/home/wyx/gaden_ws/install/pmfs_env/share/pmfs_env/launch/gaden.rviz --ros-args -r __node:=rviz2'].
[INFO] [environment-2]: process has finished cleanly [pid 1210]
![image](https://github.com/user-attachments/assets/5f55e90a-7c96-42ac-a1be-c9a58a3919cf)

**Comment by PepeOjeda** [comment]
It seems to be working correctly, since you got the message "Filament simulator finished correctly". The simulator is just really fast these days, so it finishes the entire simulation and closes in a few seconds.

**Comment by Qwxmwdncjwncc** [comment]
> It seems to be working correctly, since you got the message "Filament simulator finished correctly". The simulator is just really fast these days, so it finishes the entire simulation and closes in a few seconds.

Thank you very much for your help, as well as the contributions of you and your entire team.
