### ISSUE TITLE
To use one of the implemented algorithms, simply launch gsl_actionserver_node and create an ActionClient to send a message with the name of the chosen algorithm (see gsl_server_call.cpp for an example).

### ISSUE THREAD

**Issue by forgetto** [MAPIRlab/Gas-Source-Localization#5]
hello,
I don't understand

When it comes to how a Gas-Source-Localization simulation actually works, I add the source files to ros and compile them. Then I'm a novice. I beg those who have done this to help me, thank you very much!

**Comment by PepeOjeda** [comment]
Hello. 
The idea is that you run the `gsl_actionserver_node` (this is the node that actually handles the GSL code), and then send the server a request with the name of the method that you want to use. If you want to see examples of how to do this, see the .launch files in this repo (e.g. [this one](https://github.com/MAPIRlab/Gas-Source-Localization/blob/master/Environment%20config/Exp%20A/launch/main_simbot.launch). 

Those launch files use an additional node, `gsl_actionserver_call`, to send the request. But you can send that same request from your own code if you want, and use [the source code of the call node](https://github.com/MAPIRlab/Gas-Source-Localization/blob/master/gsl_actionserver/src/gsl_server_call.cpp) as an example on how to do that.

**Comment by forgetto** [comment]
hello,@pepeOjeda
sorry,to bother you again.

miracle@miracle-VirtualBox:/wzp_ws$ source ./devel/setup.bash
miracle@miracle-VirtualBox:/wzp_ws$ roslaunch src/Gas-Source-Localization-master/Environment config/Exp A/launch/GADEN_preprocessing.launch
RLException: [config/Exp] is neither a launch file in package [src/Gas-Source-Localization-master/Environment] nor is [src/Gas-Source-Localization-master/Environment] a launch file name
The traceback for the exception was written to the log file

After compiling, I was ready to enable the EXPA environment, and an error occurred. I don't know if you have encountered similar problems, can you help me? Thank you very much!

**Comment by PepeOjeda** [comment]
It seems like the path is not being read correctly due to having a whitespace. You should be able to fix the problem by adding quotation marks around it, or renaming the folder to `Environment_config`.

**Comment by forgetto** [comment]
hello,@pepeOjeda
Fiestly,thank you for your response.I have solved the problem successfully with your prompt.
But I found another important issue, the program does seem to have a "my_env" package, I'm not sure if it's me or if it's missing the package.
I need your help. Thank you so much.

**Comment by PepeOjeda** [comment]
I've done a pass over the config files (it's been quite a while since they were uploaded) and fixed a couple of mistakes with the package names and paths. They should all be working OK now (you have to run GADEN_preprocessing -> GADEN -> main_simbot) .

**Comment by forgetto** [comment]
Dear,@pepeOjeda
Thank you very much for your help. Your project is great. It is very friendly for beginners. And your spirit of excellence in scientific research deserves my learning.
Hats off to you and your team.
