### ISSUE TITLE
How can I run the gsl_actionserver_node

### ISSUE THREAD

**Issue by haotongluo** [MAPIRlab/Gas-Source-Localization#6]
I met with problem,I put gsl_actionserver bag in test_env/src,but I can't  run gsl_server_call.cpp

**Comment by haotongluo** [comment]
Thanks! I have solved this problem

**Comment by PepeOjeda** [comment]
Sorry for not getting to this in time. Since it seems you were able to fix it anyways, I'll close the issue.
