### ISSUE TITLE
"surge_cast" "surge_spiral" "spiral" "particle_filter"Algorithm selection and switching

### ISSUE THREAD

**Issue by forgetto** [MAPIRlab/Gas-Source-Localization#7]
hi,I'm sorry to trouble you
  Algorithm selection and switching will not be carried out in the program. We hope to get your help.If I compile my own algorithm later how can I add it to the program
 Thank you .

**Comment by PepeOjeda** [comment]
Hello.
You can select an algorithm by changing the string argument in the gsl_server_call node. If you want to implement your own algorithm you have to modify the gsl_server.cpp file to include a function that launches your code when the action request is received.
